App.EndPoint.MVC/Models/ErrorViewModel.cs
namespace App.EndPoint.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

App.EndPoint.MVC/Controllers/DutyController.cs
namespace App.EndPoint.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DutyController : Controller
    {
        private readonly IDutyAppService _DutyAppServices;
        private readonly UserManager<User> _userManager;

        public DutyController(IDutyAppService dutyAppService, UserManager<User> userManager)
        {
            _DutyAppServices = dutyAppService;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(CancellationToken cToken)
        {
            var userId = _userManager.GetUserId(User);
            var id = int.Parse(userId);
            var number = await _DutyAppServices.NumberDuty(id, cToken);

            ViewBag.TaskCount = number;
            var tasks = await _DutyAppServices.GetAllDuties(id, cToken);

            return View(tasks);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create(Duty model, CancellationToken cToken)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                model.UserId = int.Parse(userId);
                var result = await _DutyAppServices.CreateDuty(model, cToken);
                if (result.IsSuccess)
                {
                    TempData["SuccessMessage"] = result.IsMessage;
                }
                else
                {
                    TempData["ErrorMessage"] = result.IsMessage;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Preview(int id, CancellationToken cToken)
        {
            var model = await _DutyAppServices.GetDutyById(id, cToken);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id, CancellationToken cToken)
        {
            var userId = _userManager.GetUserId(User);
            var id1 = int.Parse(userId);
            var model = await _DutyAppServices.GetDutyById(id, cToken);
            if (model == null || model.UserId != id1)
                return NotFound();
            await _DutyAppServices.DeleteDuty(id, cToken);
            return RedirectToAction(nameof(Index));

        }
        [HttpGet]
        public async Task<IActionResult> Update(int id, CancellationToken cToken)
        {
            var userId = _userManager.GetUserId(User);
            var id1 = int.Parse(userId);
            var model = await _DutyAppServices.GetDutyById(id, cToken);
            if (model == null || model.UserId != id1)
                return NotFound();

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Duty model, CancellationToken cToken)
        {
            if (ModelState.IsValid)
            {
                var result = await _DutyAppServices.UpdateDuty(model, cToken);
                if (result.IsSuccess)
                {
                    ViewBag.SuccessMessage = result.IsMessage;
                }
                else
                {
                    ViewBag.ErrorMessage = result.IsMessage;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> EndTask(int id, CancellationToken cToken)
        {
            var userId = _userManager.GetUserId(User);
            var id1 = int.Parse(userId);
            var model = await _DutyAppServices.GetDutyById(id, cToken);
            if (model == null || model.UserId != id1)
                return NotFound();
            var result = await _DutyAppServices.EndDuty(id, cToken);
            if (result.IsSuccess)
            {
                ViewBag.SuccessMessage = result.IsMessage;
            }
            else
            {
                ViewBag.ErrorMessage = result.IsMessage;
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

App.EndPoint.MVC/Controllers/HomeController.cs
namespace App.EndPoint.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

App.EndPoint.MVC/Controllers/UserController.cs
namespace App.EndPoint.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserAppService _userAppService;
        private readonly SignInManager<User> _signInManager;
        public UserController(IUserAppService userAppService, SignInManager<User> signInManager)
        {
            _userAppService = userAppService;
            _signInManager = signInManager; 
        }
        [HttpGet]
        public async Task<IActionResult> Register(CancellationToken cToken)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model, CancellationToken cToken)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (string.IsNullOrWhiteSpace(model.Password) ||
                string.IsNullOrWhiteSpace(model.UserName) ||
                string.IsNullOrWhiteSpace(model.Email))
            {
                ModelState.AddModelError(string.Empty, "فیلدهای خالی را پر کنید.");
                return View(model);
            }

            var user = new User
            {
                UserName = model.UserName,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName
            };

            var result = await _userAppService.Register(user, model.Password, cToken);

            if (result.Succeeded)
            {
<<<<<<< HEAD
=======

>>>>>>> 6af6ac763dc691af9337551e93d0c8703d0db463
                return RedirectToAction("Login", "User");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        public async Task<IActionResult> Login(User user, CancellationToken cToken)
        {
            if (!ModelState.IsValid)
                return View(user);
            if (string.IsNullOrWhiteSpace(user.PasswordHash) || string.IsNullOrWhiteSpace(user.UserName))
            {
                ModelState.AddModelError(string.Empty, "فیلدهای خالی رو پر کنید.");
                return View(user);
            }
            var result = await _userAppService.Login(user.UserName, user.PasswordHash, cToken);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }

            else
            {
                ModelState.AddModelError(string.Empty, "نام کاربری یا رمز عبور اشتباه است.");
            }

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Index(CancellationToken cToken)
        {
            return View();
        }


        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }

    }
}

App.EndPoint.MVC/Views/Duty/Create.cshtml
@using App.Domain.Core.Entities
@model Duty
<div class="container px-5 my-5">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <form method="post" asp-action="Create">

        <h4>فرم ایجاد وظایف</h4><br>


        <input asp-for="Title" type="text" placeholder="عنوان وظیفه" /><br />
        <span class="text-danger" asp-validation-for="Title"></span>
        <input asp-for="Description" type="text" placeholder="توضیحات" />
      
        <button type="send" class="Transfer-btn">ثبت</button>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success">@TempData["SuccessMessage"]</div>
        }
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
        }
    </form>
</div>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

App.EndPoint.MVC/Views/Duty/Index.cshtml
@using App.Domain.Core.DTOs
@using Framework

@model List<GetDutyDto>
@{
    var taskCount = ViewBag.TaskCount;
}

<div class="table-responsive">
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">@TempData["SuccessMessage"]</div>
    }
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
    }


    <table class="table-Task" asp-action="Index">
        <thead>
            <tr>

                <td>لیست کارها</td>
                <td>
                    تعداد وظایف ناتمام :
                    <span>@taskCount</span>
                </td>
                <td><a asp-action="Create" class="btn btn-secondary" type="button">ایجاد وظیفه جدید </a></td>
            </tr>
            <tr>
                <th>شناسه</th>
                <th>عنوان</th>
                <th>توضیحات</th>
                <th>وضعیت</th>

                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
        <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Title</td>
                    <td>@item.Description</td>

                    <td>
                            @if (item.IsCompleted)
                            {
                            <span class="badge bg-success">انجام شده</span>
                            }
                            else
                            {
                            <span class="badge bg-warning">در حال انجام</span>
                            }
                    </td>
                        @*  <td>

                        <input type="hidden" name="id" value="@item.Id" />
                        <a class="btn btn-primary" asp-controller="TaskUser" asp-action="EndTask" value="@item.IsCompleted" asp-route-id="@item.Id">پایان کار</a>
                        <input type="checkbox" class="task-checkbox" asp-controller="TaskUser" asp-action="EndTask" asp-route-id="@item.Id" value="@item.IsCompleted" @(@item.IsCompleted ? "انجام شده" : "") />
                    </td> *@
                    <td>

                        <input type="hidden" name="id" value="@item.Id" />
                        <a class="btn btn-primary" asp-controller="Duty" asp-action="EndTask" value="@item.IsCompleted" asp-route-id="@item.Id">پایان</a>
                        <a class="btn btn-secondary" asp-controller="Duty" asp-action="Preview" asp-route-id="@item.Id">نمایش</a>
                        <a class="btn btn-danger" asp-controller="Duty" asp-action="Delete" asp-route-id="@item.Id">حذف</a>
                        <a class="btn btn-warning" asp-controller="Duty" asp-action="Update" asp-route-id="@item.Id">ویرایش</a>
                    </td>
                </tr>
                }
        </tbody>
        </tbody>

    </table>


</div>

App.EndPoint.MVC/Views/Duty/Preview.cshtml
@using App.Domain.Core.Entities
@model Duty
<div class="container px-5 my-5">

    <form method="post" asp-action="Preview">


        <input disabled name="Id" type="text" placeholder="شناسه" data-sb-validations="required" value="@Model.Id" />


        <input disabled asp-for="Title" type="text" placeholder="عنوان" data-sb-validations="required" value="@Model.Title" />
        <input disabled asp-for="Description" type="text" placeholder="توضیحات" data-sb-validations="required" value="@Model.Description" />
        <input disabled asp-for="IsCompleted" type="text" placeholder="وضعیت" data-sb-validations="required" value="@Model.IsCompleted" />

    </form>
</div>

App.EndPoint.MVC/Views/Duty/Update.cshtml
@using App.Domain.Core.Entities
@model Duty
<div class="container px-5 my-5">

    <form method="post" asp-action="Update">


        <input asp-for="Title" type="text" placeholder="عنوان" value="@Model.Title" />
        <span class="text-danger" asp-validation-for="Title"></span>
        <input asp-for="Description" type="text" placeholder="توضیحات" value="@Model.Description" />
        <span class="text-danger" asp-validation-for="Description"></span>
        <label class="checkbox-container">
            <span>کار انجام شده؟</span>
            <input asp-for="IsCompleted" class="task-checkbox" type="checkbox" placeholder="وضعیت" value="True" />

        </label>

        <span class="text-danger" asp-validation-for="IsCompleted"></span>
        <button type="send" class="Transfer-btn">ثبت ویرایش</button>
        @if (ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success">@ViewBag.SuccessMessage</div>
        }
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
        }

    </form>
</div>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

App.EndPoint.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

App.EndPoint.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App.EndPoint.MVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.EndPoint.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">وظایف</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Duty" asp-action="Index" asp-route-id="UserTaId">لیست کارهای من</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">خروج</a>
                            </li>
                        }
                        
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">ثبت نام</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">ورود </a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - App.EndPoint.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

App.EndPoint.MVC/Views/User/Login.cshtml
@using App.Domain.Core.Entities
@model User
<div class="page">

    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }
    <form class="login-form" method="post" asp-action="Login">

        <h4>ورود </h4><br>


        <input asp-for="UserName" placeholder="نام کاربری" type="text">
        <span class="text-danger" asp-validation-for="UserName"></span>
        <input asp-for="PasswordHash" placeholder="رمز عبور" type="password"><br><br>
        <span class="text-danger" asp-validation-for="PasswordHash"></span>
        <button type="send" class="login-btn">ورود</button>

        @if (ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success">@ViewBag.SuccessMessage</div>
        }
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
        }


    </form>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

App.EndPoint.MVC/Views/User/Register.cshtml
@using App.Domain.Core.DTOs
@using App.Domain.Core.Entities
@model RegisterViewModel
<div class="page">
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }

    <form class="register-form" method="post" asp-action="Register">
<<<<<<< HEAD
        <img src="~/pic/logo.png" alt="logo">
        <h4>ثبت نام</h4><br>
=======

        <h4>ثبت نام </h4><br>

>>>>>>> 6af6ac763dc691af9337551e93d0c8703d0db463

        <input placeholder="نام کاربری" type="text" asp-for="UserName"><br>
        <span class="text-danger" asp-validation-for="UserName"></span>

        <input placeholder="ایمیل" type="email" asp-for="Email"><br>
        <span class="text-danger" asp-validation-for="Email"></span>

        <input placeholder="رمز عبور" type="password" asp-for="Password"><br><br>
        <span class="text-danger" asp-validation-for="Password"></span>

        <input placeholder="نام" type="text" asp-for="FirstName"><br>
        <input placeholder="نام خانوادگی" type="text" asp-for="LastName"><br>

        <button type="submit" class="register-btn">ثبت نام</button>
    </form>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}